### ISSUE TITLE
Review for Project01

### ISSUE THREAD

**Issue by zezhi994** [jdh8v/istm-6212#1]
Hello jhurwitz, 
this is my review for your project01. I was able to run your notebook at my computer successfully. You did a Great job!

**Problem 1**
Part A
Your result is different from mine. It’s great that you use very specific markdown to show the steps, which help me easily know how you think about this problem. You said that consider matches regardless of upper/lower case. However, I considered about upper/lower case when I did this part, since I think the question asked about people’ names, and the initial letter should be uppercase. 
Part B
Our results match perfectly! I liked the way you solve this problem. It took me too much time to think about this question when I did it. I didn’t think about finding “Rom.” and “Jul.” in the txt file at first. You got the point so quickly and solve it efficiently.

**Problem 2**
Part A
We got the same results this part. I liked that you use “csvstat” and “csvlook” to make the csv file more clear when you manage the data. I didn’t think about it before. 
Part B
We got the same results this part. I liked that you put the result into a new csv file, which seems more structured. I also liked that you add how many times the bike IDs appeared in front of the bike ID. 

**Problem 3**
Part A
I liked that you put the results of using pipeline and filter together and made it easy for readers to understand. I also liked that you had tried your best to find the solution. Your spirit of study deserves to be learned.
Part B
I liked that you used all the filter you had created to solve this problem.

**Extra credit**
I am sorry I didn’t find the answer of this part.

**Comment by jdh8v** [comment]
Thanks!
