### ISSUE TITLE
Review for poject01

### ISSUE THREAD

**Issue by zzq126** [jdh8v/istm-6212#2]
Hi jhurwitz,
I was able to run your file in jupyter notebook and you have done a great job in completing Project 1! I really appreciate your detailed markdowns which help me easily understand your code.
Here are a few things you could keep an eye out for next time:
1. For part A of question 1, we got similar answers but I think it may be better to take upper case into consideration because it is a name of a person.
2.In question 2, we got the same answer and even our methods are the same!
3.For question 3, I noticed that the output of your filter 'split.py' is sort of different because you have not excluded words whose character is less than 2. You could try to learn python package "re" and it may solve your problem. Other filters work fine!
4.The extra credits seem to be incomplete. 

Hope that could help.
All the best!

Best,
Ziqing Zhu

**Comment by jdh8v** [comment]
Thanks!
