### ISSUE TITLE
Project 2 Review - Eugene Hwang #1

### ISSUE THREAD

**Issue by euhwang** [jdh8v/istm-6212#3]
Hi Jon,

Great job on completing your second project! I was able to run your python notebook successfully on my datanotebook.org.

I liked how use you used the coalesce expression to consider the nulls in the data and I liked how you check that there was no nulls in the data aftewards.

I liked how you separated the longitude and latitude in its own separate columns. This will make it easier for analyst.

I liked how your create statement for your fact table was very succinct and efficient. I updated my fact table using multiple queries but will will look into optimizing my create statement in the future.

I like the seaborn graphs. It made visualing the data a lot easier.

I would suggest adding more counts in the fact table. For example, you could have created a binary count for each type of crime (description) or weapons used, instead of counting the description in the DIM_CRIME_DETAILS table. This could potentially speed up the query. 

I would have liked to see the star schema in the data notebook. Since I did not have Visio 2016, I had to install a compability program to view the star schema. 

Great job!

Eugene

**Comment by jdh8v** [comment]
Thanks!

**Comment by jdh8v** [comment]
Also, I added a PDF of the Visio diagram. Should have thought of that earlier but thanks again.

**Comment by euhwang** [comment]
Oh did you? Sorry, I must have missed that.

**Comment by jdh8v** [comment]
Nope, I just added it this morning. You didn't miss it ;-)
