### ISSUE TITLE
Review of Project 02 by Qinhui

### ISSUE THREAD

**Issue by xqh0104** [jdh8v/istm-6212#4]
Hi Jon,

You did a great job on completing your second project. I downloaded your code, and I can smoothly run the code on datanotebook.org.
## First Question
For the first question, I think your annotation is really clear. Though the data I selected for the project 2 is not about crime, but I can know the content of crime data and how you deal with it clearly.
## Second Question
For the second question, I really liked the EXTRACT expression you used to make column year month and day.
## Third Question
For the third question, I noticed that you use a COALESCE expression to deal with null variables, but what I do is use update expression to set the NULL variables ‘NULL’. The way you do it is really easier. 
And in the step3, you used substring to separate latitude and longitude. Before reading your code, I didn’t realize I can separate geo location using substring.
In the step4, the way you build the fact table is really efficient. I did it using multiple queries.
## Fourth Question
For the fourth question, you used seaborn to visualize the query result. It’s so nice. I learned from that.

I tried to open the diagram you upload in github, but I didn’t install visio. So maybe next time you can have a screenshot of it.

I learned a lot from your project.

Thank you,
Qinhui

**Comment by jdh8v** [comment]
Thanks Qinhui! I added a PDF of the Visio diagram. Should have thought about that up front.
